### ISSUE TITLE
Middle pack freezes in late game

### ISSUE THREAD

**Issue by outrowender** [guilhermebkel/uno-game#25]
Sometimes in late game with 6 players, the middle pack freezes and not show the actual card for all players in room. The game continues, but we only knew wich card is because of the cards wich can be played, start to glow.

**Comment by guilhermebkel** [comment]
Hey @outrowender, thanks for reporting that bug :)

What do you mean is like, sometimes in the game with a full room (with multiple cards drawn), the top card on the center of the game shows per example a "3-red" card by mistake but the correct card is a "4-yellow"?

When this happens again, can you try to refresh the page in order to know if the correct card is shown? (it is because I think this bug is something related to having a lot of cards rendered on client, so probably the fix needs to be done there)

**Comment by outrowender** [comment]
> the top card on the center of the game shows per example a "3-red" card by mistake but the correct card is a "4-yellow

Yes @guilhermebkel! I will try refresh the page if happens again!

**Comment by GlowingUmbreon** [comment]
This happens when there are too many cards in the middle, a refresh will fix it.

**Comment by guilhermebkel** [comment]
Got it @GlowingUmbreon! I was thinking about limiting the amount of cards in the middle (rendered by front-end), what do you think?

**Comment by GlowingUmbreon** [comment]
Definitely, My and my friends had to refresh the game every couple of minutes over-wise it would become unplayable.

**Comment by guilhermebkel** [comment]
Sure! Fixed at https://github.com/guilhermebkel/uno-game/commit/10a42a4d223c8f2c50f404277effa2ee7bfe107f

**Comment by GlowingUmbreon** [comment]
> Sure! Fixed at [10a42a4](https://github.com/guilhermebkel/uno-game/commit/10a42a4d223c8f2c50f404277effa2ee7bfe107f)

Has this been published to the website? I was playing with my friends earlier this week and it still appeared to occur.

**Comment by guilhermebkel** [comment]
@GlowingUmbreon Yep, it was published. Can you try cleaning up browser cache in other to see if this problem happens again? _(I'm currently having some trouble with service worker creating cache on front end and deploys not working)_
